### ISSUE TITLE
Problems with Windows

### ISSUE THREAD

**Issue by Elteoremadebeethoven** [krassowski/jupyter-manim#1]
First of all, I want to congratulate you for your incredible work, it works great on Mac, but I have problems with Windows.
Mac:
![Captura de pantalla 2019-05-25 a la(s) 03 15 32](https://user-images.githubusercontent.com/43224662/58366671-6a4d6b00-7e9b-11e9-89e0-30abf2c19a17.png)

I'm not an advanced user of jupyter, do you think this can be solved if I install anaconda?
Windows:

![jupyter](https://user-images.githubusercontent.com/43224662/58366698-c2846d00-7e9b-11e9-8b61-f58c438b46a8.jpg)

Thank you!

**Comment by krassowski** [comment]
I will look into that. The traceback seems to be trimmed (I cannot see the last exception fully) - would you be able to take another screenshot after scrolling down a bit?

**Comment by Elteoremadebeethoven** [comment]
Sorry, my bad. If I'm not mistaken it has to do with the double diagonals.

![jupyter](https://user-images.githubusercontent.com/43224662/58372877-30f01c00-7eea-11e9-8df4-13ab53301ac7.jpg)

**Comment by jaymefosa** [comment]
I am having the same issue, same error, same temp folder + string.py. Anaconda is installed for me. Windows 7. Manim imports and I can access the namespace. I've tried the typical "open cmd with administrator" suggestion when jupyter notebook has a permissions error.

**Comment by krassowski** [comment]
So this is an issue with Python implementation of temporary files on Windows:
- https://stackoverflow.com/a/15590253/6646912
- https://stackoverflow.com/q/15169101/6646912

I have published 0.11 version which attempts to work around this issue, though I have not tested it on Windows. It would be of great help if you could update the package and let me know if this works.

To update with pip:

```
python3 -m pip install jupyter_manim --upgrade
```

To verify that update succeeded:
```python
import jupyter_manim
print(jupyter_manim.__version__)    # should print 0.11
```

**Comment by jaymefosa** [comment]
Ohhh fantastic this works! Thank you!

Just a heads up for others who have had issues getting the C compiler to work right, cl.exe, on Windows: if you download pycairo 1.18 and install it locally with pip, then use 'pip install jupyter-manim', you might still get some error about cairo wheel build failing. However, jupyter-manim is probably installed correctly  (it was for me).

**Comment by krassowski** [comment]
Thank you. I will close this issue for now, but feel free to reopen if any of you have further problems using this package on Windows. I will try provide better installation instructions for Windows at some point (possibly next weekend).
